name: PR Check
on:
  pull_request:
    types: [opened, reopened]
jobs:
  gh-pages-deploy:
    name: Ensure App Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Deps
        run: yarn install
      - name: Build dist
        run: yarn build
